default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-xml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: detect-private-key
      - id: mixed-line-ending
        args: ["--fix=lf"]
        description: Forces to replace line ending by the UNIX 'lf' character.
      - id: check-executables-have-shebangs
        name: "Executable text files have shebangs"
      - id: check-symlinks
        types: ["symlink"]
        types_or: ["symlink"]
        stages: [manual]

  - repo: https://github.com/ansible/ansible-lint.git
    rev: v6.22.1
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$

  - repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.18
    hooks:
      - id: forbid-binary
        exclude: .png|.jpg
      - id: shellcheck
      - id: go-fmt
  - repo: https://github.com/ibm/detect-secrets
    rev: 0.13.1+ibm.61.dss
    hooks:
      - id: detect-secrets
        args:
          [
            "--baseline",
            ".secrets.baseline",
            "--fail-on-unaudited",
            "--use-all-plugins",
          ]
        exclude: go.sum|module-metadata.json
