namespace: "ibm"
name: "power_linux_sap"
version: 3.0.0
readme: "README.md"
description: Collection of Ansible Roles for RHEL/SLES OS to prepare LPARs for installing SAP on Power Systems.
authors:
  - Sahitya Jain <sahityajain(at)in.ibm.com>
  - Suraj Bharadwaj <suraj.bharadwaj(at)ibm.com>

license_file: "LICENSE"
tags:
  - power
  - sap
  - rhel
  - sles
  - ibm
  - cloud
  - linux
  - networking
  - storage
  - powervs

dependencies: {}
repository: "https://github.com/IBM/ansible-power-linux-sap"
documentation: "https://github.com/IBM/ansible-power-linux-sap/README.md"
homepage: "https://github.com/IBM/ansible-power-linux-sap"
issues: "https://github.com/IBM/ansible-power-linux-sap/issues"
