namespace: "ibm"
name: "power_linux_sap"
version: "1.1.4"
readme: "README.md"
description: RHEL/SLES ansible automation to prepare LPARs for installing SAP on Power Systems.
authors:
  - "Sahitya Jain(@sahityajain123), Suraj Bharadwaj(@surajsbharadwaj)"

license_file: "LICENSE"
tags:
  - power
  - sap
  - rhel
  - sles
  - ibm

dependencies: {}
repository: "https://github.com/IBM/ansible-power-linux-sap"
documentation: "https://github.com/IBM/ansible-power-linux-sap"
homepage: "https://github.com/IBM/ansible-power-linux-sap"
issues: "https://github.com/IBM/ansible-power-linux-sap/issues"
