namespace: "sahityajain123"

name: "ansible_power_linux_sap"

version: "0.1"

readme: "README.md"

authors:
- "Sahitya Jain, Suraj Bharadwaj"

description: RHEL/SLES ansible automation to prepare LPARs for installing SAP on Power Systems.

license_file: "LICENSE"

tags:
- power
- sap
- rhel
- sles
- ibm

dependencies: {}

repository: "https://github.com/IBM/ansible-power-linux-sap"

documentation: "https://github.com/IBM/ansible-power-linux-sap"

homepage: "https://github.com/IBM/ansible-power-linux-sap"

issues: "https://github.com/IBM/ansible-power-linux-sap/issues"
