
# copy this file to roles/monitoring_sap/vars/main.yml and put in your SAP System parameters

#monitoring meta parameter

sap_monitoring_action: add
#sap_monitoring_action: delete


sap_monitoring_nr: "11"
# sap_monitoring_nr: "95"
sap_monitoring_solution_name: "PM2 6.1 (S/4 2022)"

# IBM cloud parameters
ibmcloud_monitoring_instance_url: https://ingest.prws.private.br-sao.monitoring.cloud.ibm.com/prometheus/remote/write 
ibmcloud_monitoring_authorization_credentials: d9209057-f8c5-4f4d-a644-3400c261d572
#ibmcloud_monitoring_authorization_credentials: 30262cb2-b114-4b69-9873-fbc93cb2afd9

#hana parameters
sap_hana_ip: 10.51.0.8
sap_hana_http_port: 50213
sap_hana_sql_systemdb_port: 30213
sap_hana_sql_systemdb_user: monitoring-user
sap_hana_sql_systemdb_password: NewPass123$

#netweaver_parameters
sap_ascs_ip: 10.51.0.81
sap_ascs_http_port: 50013
sap_app_server:
  - sap_app_server_nr: 01
    ip: 10.51.0.81
    port: 50113
  - sap_app_server_nr: 02
    ip: 10.51.0.81
    port: 50113
  - sap_app_server_nr: 03
    ip: 10.51.0.81
    port: 50113

