---
####################################
# Block: configure proxy settings
####################################

- name: Configure proxy settings
  when: client_config.squid.enable | default(false) | bool
  block:
    - name: Set fact for bash_file when OS is RHEL
      ansible.builtin.set_fact:
        bash_file: /etc/bashrc
      when: ansible_distribution is match("RedHat*")

    - name: Set fact for bash_file when OS is SLES
      ansible.builtin.set_fact:
        bash_file: /etc/bash.bashrc
      when: ansible_distribution is match("SLES*")

    # If http_proxy entries exists, then update the http_proxy entries with passed squid server ip and port.
    - name: Update http_proxy entries in /etc/bashrc or /etc/bash.bashrc file
      ansible.builtin.replace:
        path: "{{ bash_file }}"
        regexp: "^(.*){{ item }}(.*)$"
        replace: "export {{ item }}=http://{{ client_config.squid.squid_server_ip_port }}"
      with_items:
        - http_proxy
        - https_proxy
        - HTTP_PROXY
        - HTTPS_PROXY
      register: replace_log
      when: client_config.squid.squid_server_ip_port is defined

    # If http_proxy entries are absent(status obtained from previous register value), then http_proxy entries will be added.
    - name: Insert http_proxy entries in /etc/bashrc or /etc/bash.bashrc file if not present
      ansible.builtin.lineinfile:
        path: "{{ bash_file }}"
        regexp: "^(.*){{ item }}(.*)$"
        line: "export {{ item }}=http://{{ client_config.squid.squid_server_ip_port }}"
      with_items:
        - http_proxy
        - https_proxy
        - HTTP_PROXY
        - HTTPS_PROXY
      when:
        - client_config.squid.squid_server_ip_port is defined
        - not replace_log.changed

    # On RHEL: If proxy entry exist in /etc/dnf/dnf.conf then modify the value.
    - name: Modify proxy entry in /etc/dnf/dnf.conf file on RHEL OS
      ansible.builtin.replace:
        path: "/etc/dnf/dnf.conf"
        regexp: "proxy(.*)$"
        replace: "proxy=http://{{ client_config.squid.squid_server_ip_port }}"
      register: replace_dnf_log
      when: client_config.squid.squid_server_ip_port is defined and ansible_distribution is match("RedHat*")

    # On RHEL: If proxy entry is absent(status obtained from previous register value), then proxy will add be added to the /etc/dnf/dnf.conf file.
    - name: Insert proxy entry in /etc/dnf/dnf.conf file on RHEL OS if not present
      ansible.builtin.lineinfile:
        path: "/etc/dnf/dnf.conf"
        regexp: "proxy(.*)$"
        line: "proxy=http://{{ client_config.squid.squid_server_ip_port }}"
      when:
        - client_config.squid.no_proxy_hosts is defined
        - not replace_dnf_log.changed

    # If no_proxy entry exists, then modify with the values passed in.
    - name: Modify no_proxy entry in in /etc/bashrc or /etc/bash.bashrc file
      ansible.builtin.replace:
        path: "{{ bash_file }}"
        regexp: "^(.*)no_proxy(.*)$"
        replace: "export no_proxy={{ client_config.squid.no_proxy_hosts }}"
      register: replace_noproxy_log
      when: client_config.squid.no_proxy_hosts is defined

    # If no_proxy is absent(status obtained from previous register value), then no_proxy will add be added.
    - name: Insert no_proxy entriy in in /etc/bashrc or /etc/bash.bashrc file if not present
      ansible.builtin.lineinfile:
        path: "{{ bash_file }}"
        regexp: "^(.*)no_proxy(.*)$"
        line: "export no_proxy={{ client_config.squid.no_proxy_hosts }}"
      when:
        - client_config.squid.no_proxy_hosts is defined
        - not replace_noproxy_log.changed

    - name: Verify connection to internet
      ansible.builtin.uri:
        url: http://www.google.com

####################################
# Block: install DNS
####################################
- name: Install bind-utils for DNS
  when: client_config.dns.enable | default(false) | bool
  block:
    - name: Installing bind-utils
      ansible.builtin.package:
        name: bind-utils
        state: present

    - name: Modifying /etc/resolv.conf file to add nameserver
      ansible.builtin.lineinfile:
        path: /etc/resolv.conf
        line: nameserver {{ client_config.dns.dns_server_ip }}

    - name: Pause for 60 sec
      ansible.builtin.pause:
        seconds: 60

    - name: Check for name resolution using dig command
      ansible.builtin.command: dig -i www.google.com +short
      register: dig_output
      changed_when: false
      ignore_errors: true

    - name: Verify if dig command returned an IP
      ansible.builtin.fail:
        msg: "DNS is not working, please verify setting"
      when: dig_output.stdout is not ansible.utils.ipv4
      ignore_errors: true

####################################
# Block: install NTP
####################################
- name: Install Chrony for NTP
  when: client_config.ntp.enable | default(false) | bool
  block:
    - name: Installing chrony
      ansible.builtin.package:
        name: chrony
        state: present

    - name: Replace iburst line in /etc/chrony.conf file
      ansible.builtin.replace:
        path: /etc/chrony.conf
        regexp: "^(.*)iburst$"
        replace: "server {{ client_config.ntp.ntp_server_ip }} iburst"

    - name: Start chronyd service
      ansible.builtin.service:
        name: chronyd
        state: restarted
        enabled: true
      changed_when: false

    - name: Pause for 60 sec
      ansible.builtin.pause:
        seconds: 60

    - name: Verify Chrony configuration grepping for Leap status Normal using chronyc tracking
      ansible.builtin.command: chronyc tracking | grep Leap | grep Normal
      changed_when: false

####################################
# Block: install NFS and mount
####################################
- name: Install NFS-utils
  when: client_config.nfs.enable | default(false) | bool
  block:
    - name: Install NFS client package
      ansible.builtin.package:
        name: nfs-utils
        state: latest

    - name: Start and enable NFS client service
      ansible.builtin.service:
        name: nfs-client.target
        state: restarted
        enabled: true
      changed_when: false

    - name: Create the NFS directory if it does not exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      with_items: "{{ client_config.nfs.nfs_client_path.split(';') }}"

    # Mount NFS directory. server_path, should be "server_name":"source_path"
    - name: Mount NFS directory
      ansible.posix.mount:
        path: "{{ item.0 }}"
        src: "{{ item.1 }}"
        state: mounted
        boot: true
        opts: defaults,nofail
        fstype: nfs
      with_together:
        - "{{ client_config.nfs.nfs_client_path.split(';') }}"
        - "{{ client_config.nfs.nfs_server_path.split(';') }}"

    - name: Verify if mount point is accessible
      ansible.builtin.command: "ls -l {{ item }}"
      loop: "{{ client_config.nfs.nfs_client_path.split(';') }}"
      changed_when: false
