---
## To modify bashrc file to add squid proxy
- name: Modify the file bashrc to add squid proxy
  when: client_config.squid.enable | default(false) | bool
  block:
    - name: Set the variable for the bashrc file if OS is RHEL
      ansible.builtin.set_fact:
        bash_file: /etc/bashrc
      when: ansible_distribution is match("RedHat*")
    - name: Set the variable for the bashrc if OS is SLES
      ansible.builtin.set_fact:
        bash_file: /etc/bash.bashrc
      when: ansible_distribution is match("SLES*")

    # Check if http_proxy entries are already present. If yes, don't add new entries. If no, it should be added.
    - name: Check for http proxy entries in {{ bash_file }}
      ansible.builtin.replace:
        path: "{{ bash_file }}"
        regexp: "^(.*){{item}}(.*)$"
        replace: "export {{item}}=http://{{ client_config.squid.squid_server_ip_port }}"
      with_items:
        - http_proxy
        - https_proxy
        - HTTP_PROXY
        - HTTPS_PROXY
      register: replace_log
      when: client_config.squid.squid_server_ip_port is defined

    # In case no entries were present, next task, will add the first time entries.
    - name: Check for http proxy entries in {{ bash_file }}
      ansible.builtin.lineinfile:
        path: "{{ bash_file }}"
        regexp: "^(.*){{item}}(.*)$"
        line: "export {{item}}=http://{{ client_config.squid.squid_server_ip_port }}"
      with_items:
        - http_proxy
        - https_proxy
        - HTTP_PROXY
        - HTTPS_PROXY
      when:
        - client_config.squid.squid_server_ip_port is defined
        - not replace_log.changed

    # Check if no_proxy entries are already present. If yes, don't add new entries. If no, it should be added.
    - name: Check for http proxy entries in {{ bash_file }}
      ansible.builtin.replace:
        path: "{{ bash_file }}"
        regexp: "^(.*)no_proxy(.*)$"
        replace: "export no_proxy={{ client_config.squid.no_proxy_hosts }}"
      register: replace_noproxy_log
      when: client_config.squid.no_proxy_hosts is defined

    # In case no no_proxy entries were present, next task, will add the first time entries.
    - name: Check for http proxy entries in {{ bash_file }}
      ansible.builtin.lineinfile:
        path: "{{ bash_file }}"
        regexp: "^(.*)no_proxy(.*)$"
        line: "export no_proxy={{ client_config.squid.no_proxy_hosts }}"
      when:
        - client_config.squid.no_proxy_hosts is defined
        - not replace_noproxy_log.changed

    - name: Verify connection to internet
      ansible.builtin.uri:
        url: http://www.google.com

# This block will update DNS
- name: Updating DNS
  when: client_config.dns.enable | default(false) | bool
  block:
    ## Installing bind-utils
    - name: Installing bind-utils
      ansible.builtin.package:
        name: bind-utils
        state: present

    - name: Modifying /etc/resolv.conf file to add nameserver
      ansible.builtin.lineinfile:
        path: /etc/resolv.conf
        line: nameserver {{ client_config.dns.dns_server_ip }}

    - name: Pause for 60 sec
      ansible.builtin.pause:
        seconds: 60

    - name: Check for name resolution using dig command
      ansible.builtin.command: dig -i www.google.com +short
      register: dig_output
      changed_when: false
    - name: Output the dig command results
      ansible.builtin.debug:
        var: dig_output.stdout
    - name: Verify if dig command returned an IP
      ansible.builtin.fail:
        msg: "DNS is not working, please verify setting"
      when: dig_output.stdout is not ansible.utils.ipv4

# This block will configure NTP
- name: Configure DNS
  when: client_config.ntp.enable | default(false) | bool
  block:
    ## Installing chrony
    - name: Installing chrony
      ansible.builtin.package:
        name: chrony
        state: present

    ## Modifying /etc/chrony.conf file
    - name: Replace iburst line in /etc/chrony.conf file
      ansible.builtin.replace:
        path: /etc/chrony.conf
        regexp: "^(.*)iburst$"
        replace: "server {{ client_config.ntp.ntp_server_ip }} iburst"

    ## Starting chronyd service
    - name: Start chronyd service
      ansible.builtin.service:
        name: chronyd
        state: restarted
        enabled: true
      changed_when: false

    - name: Pause for 60 sec
      ansible.builtin.pause:
        seconds: 60

    - name: Verify Chrony configuration grepping for Leap status Normal using chronyc tracking
      ansible.builtin.command: chronyc tracking | grep Leap | grep Normal
      changed_when: false

# This block will Install NFS client and mount NFS exported directories locally
- name: Install NFS Client and mount NFS exported directories
  when: client_config.nfs.enable | default(false) | bool
  block:
    - name: Install NFS client package
      ansible.builtin.package:
        name: nfs-utils
        state: latest

    - name: Start and enable NFS client service
      ansible.builtin.service:
        name: nfs-client.target
        state: restarted
        enabled: true
      changed_when: false

    - name: Create the NFS directory if it does not exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      with_items: "{{ client_config.nfs.nfs_client_path.split(';') }}"

    # Mounting NFS directory. server_path, should be "server_name":"source_path"
    - name: Mount NFS directory
      ansible.posix.mount:
        path: "{{ item.0 }}"
        src: "{{ item.1 }}"
        state: mounted
        boot: true
        opts: defaults,nofail
        fstype: nfs
      with_together:
        - "{{ client_config.nfs.nfs_client_path.split(';')  }}"
        - "{{ client_config.nfs.nfs_server_path.split(';')  }}"

    - name: Verify if mount point is accessible
      ansible.builtin.command: "ls -l {{ item }}"
      loop: "{{ client_config.nfs.nfs_client_path.split(';')  }}"
      changed_when: false
