---
# 2 blocks executing 2 different actions, controlled by the customer variable  sap_monitoring_action (add/delete)
# these Ansible tasks are NOT idempotent on purpose due to the actions:
# existing configurations are overwritten on purpose

########################################################################################
#  Block: Delete one SAP monitoring configuration with the specific  <sap_monitoring_nr>
########################################################################################

- name: Delete the SAP monitoring configuration with the specific <sap_monitoring_nr>

  when: sap_monitoring_action == "delete"
  block:

    - name: Check existence of the SAP and monitoring variables
      ansible.builtin.fail:
        msg: 'variable {{ sap_monitoring_nr }} is not defined but required'
      when: sap_monitoring_nr is not defined

    - name: Delete one SAP monitoring configuration
      ansible.builtin.include_tasks: sap-monitoring-configuration-deletion.yml


############################################################
#  Block: Add a SAP System to the monitoring configuration
############################################################

- name: Add a SAP System to the monitoring configuration
  when: sap_monitoring_action == "add"
  block:

    - name: Ensure required variables are defined
      ansible.builtin.assert:
        that:
          - "{{ sap_monitoring_nr is defined}}"
          - "{{ sap_tools_directory is defined}}"
          - "{{ ibmcloud_monitoring_instance_url is defined}}"
          - "{{ ibmcloud_monitoring_authorization_credentials is defined}}"
          - "{{ sap_hana_ip is defined}}"
          - "{{ sap_hana_http_port is defined}}"
          - "{{ sap_hana_sql_systemdb_port is defined}}"
          - "{{ sap_hana_sql_systemdb_user is defined}}"
          - "{{ sap_hana_sql_systemdb_password is defined}}"
          - "{{ sap_ascs_ip is defined}}"
          - "{{ sap_ascs_http_port is defined}}"
          - "{{ sap_app_server is defined}}"
        fail_msg: "The variable is not defined but required."

    - name: Check existing SAP monitoring configurations on the same <sap_monitoring_nr>
      ansible.builtin.stat:
        path: /etc/prometheus/{{ sap_monitoring_nr }}.yml
      register: prometheus_agent_yml

    - name: Check existing SAP monitoring configurations on the same <sap_monitoring_nr>
      ansible.builtin.fail:
        msg:
          - "The <sap_monitoring_nr> {{ sap_monitoring_nr }} is already in use with a SAP monitoring configuration."
          - "In case you want to override the existing monitoring configuration, set the parameter <config_override> to true."
      when: prometheus_agent_yml.stat.exists and not config_override

    - name: Check requirements on OS and applications
      ansible.builtin.include_tasks: check-requirements.yml

      # checks, if SAP_HANA_CLIENT DB-driver is installed on the monitoring host
    - name: Check existence of /usr/lib64/python3.6/site-packages/hdbcli/dbapi.py
      ansible.builtin.stat:
        path: /usr/lib64/python3.6/site-packages/hdbcli/dbapi.py
      register: file_hana_driver

      # checks, if SAP_HANA_CLIENT /usr/sap/hdbclient/hdbuserstore is installed on the monitoring host
    - name: Check existence of /usr/sap/hdbclient/hdbuserstore
      ansible.builtin.stat:
        path: /usr/sap/hdbclient/hdbuserstore
      register: file_hana_hdbuserstore

    - name: If SAP HANA client does not exist then install SAP HANA client
      ansible.builtin.include_tasks: "{{ task }}.yml"
      loop_control:
        loop_var: task
      loop:
        - repos-activation
        - sap-hana-client-installation
      when: not file_hana_driver.stat.exists or not file_hana_hdbuserstore.stat.exists

    - name: Add one SAP System to the monitoring configuration
      ansible.builtin.include_tasks: "{{ task }}.yml"
      loop_control:
        loop_var: task
      loop:
        - check-requirements
        - port-connectivity-check
        - sap-host-exporter-configuration
        - hanadb-exporter-configuration
        - prometheus-agent-configuration
