---
# This playbook checks port connectivity to SAP System ports on the monitoring host
- name: This playbook deploys the SAP monitoring configuration on the monitoring host
  ansible.builtin.debug:
    msg: "SAP monitoring configuration using the sap_monitoring_nr: {{ sap_monitoring_nr }}"

- name: Install netcat-openbsd
  community.general.zypper:
    name: netcat-openbsd
    state: present
  tags: netcat-openbsd

- name: Check network connectivity to SAP System, fail if ports are not open
  ansible.builtin.command: "{{ netcat_item }}"
  loop_control:
    loop_var: netcat_item
  loop:
    - "netcat -vz {{ sap_hana_ip }} {{ sap_hana_sql_systemdb_port }}"
    - "netcat -vz {{ sap_hana_ip }} {{ sap_hana_http_port }}"
    - "netcat -vz {{ sap_ascs_ip }} {{ sap_ascs_http_port }}"
  register: command_result
  failed_when: "'failed' in command_result.stderr"
  changed_when: false

- name: Check network connectivity to SAP App servers, fail if ports are not open
  ansible.builtin.command: "netcat -vz {{ server_item.ip }} {{ server_item.port }}"
  loop_control:
    loop_var: server_item
  loop: "{{ sap_app_server }}"
  register: command_result
  failed_when: "'failed' in command_result.stderr"
  changed_when: false
