---
# The role common will activate SLES OS Repos and install the prometheus packages

- name: Install netcat-openbsd
  ansible.builtin.zypper:
    name: netcat-openbsd
    state: present
  tags: netcat-openbsd

- name: Activate SLES repo SLE-Module-SAP-Applications15-SP5-Updates & SLE-Module-Packagehub-Subpackages15-SP5-Pool
  ansible.builtin.command: "{{ item_cmd }}"
  loop:
    - /usr/sbin/SUSEConnect -p sle-module-sap-applications/{{ ansible_distribution_version }}/x86_64
    - /usr/sbin/SUSEConnect -p PackageHub/{{ ansible_distribution_version }}/x86_64
  loop_control:
    loop_var: item_cmd
