# This playbook will delete one monitoring configuration on the monitoring host

- name: This playbook deletes one SAP monitoring configuration on the monitoring host
  ansible.builtin.debug:
    msg: "SAP monitoring number to delete: {{ sap_monitoring_nr }}"
  when: sap_monitoring_action == "delete"

- name: Stop and disable systemd daemon prometheus@{{ sap_monitoring_nr }}
  ansible.builtin.systemd:
    name: prometheus@{{ sap_monitoring_nr }}
    state: stopped
    enabled: false
  ignore_errors: true

- name: Stop and disable systemd daemon prometheus-hanadb_exporter@config-{{ sap_monitoring_nr }}-SQL
  ansible.builtin.systemd:
    name: prometheus-hanadb_exporter@config-{{ sap_monitoring_nr }}-SQL
    state: stopped
    enabled: false
  ignore_errors: true

- name: Stop and disable systemd daemon sap_host_exporter@sap_host_exporter-{{ sap_monitoring_nr }}-ASCS
  ansible.builtin.systemd:
    name: sap_host_exporter@sap_host_exporter-{{ sap_monitoring_nr }}-ASCS
    state: stopped
    enabled: false
  ignore_errors: true

- name: Stop and disable systemd daemon sap_host_exporter@sap_host_exporter-{{ sap_monitoring_nr }}-HANA
  ansible.builtin.systemd:
    name: sap_host_exporter@sap_host_exporter-{{ sap_monitoring_nr }}-HANA
    state: stopped
    enabled: false
  ignore_errors: true

- name: Disable systemd daemon sap_host_exporter@sap_host_exporter-{{ sap_monitoring_nr }}-DI-*
  ansible.builtin.shell: /usr/bin/rm -f /etc/systemd/system/multi-user.target.wants/sap_host_exporter@sap_host_exporter-{{ sap_monitoring_nr }}-DI-*.service
  ignore_errors: true

- name: Stop systemd daemon sap_host_exporter@sap_host_exporter-{{ sap_monitoring_nr }}-DI-*
  ansible.builtin.shell: systemctl stop sap_host_exporter@sap_host_exporter-{{ sap_monitoring_nr }}-DI* # noqa: command-instead-of-module
  ignore_errors: true

# module systemd: globbing for start, but not for disable
#  systemctl status sap_host_exporter@sap_host_exporter-{{ sap_monitoring_nr }}-DI*
# /etc/systemd/system/multi-user.target.wants/sap_host_exporter@sap_host_exporter-03-DI-2.service

### delete configuration files

- name: Delete file /etc/prometheus/{{ sap_monitoring_nr }}.yml
  ansible.builtin.file:
    path: /etc/prometheus/{{ sap_monitoring_nr }}.yml
    state: absent
  ignore_errors: true

- name: Delete file /etc/hanadb_exporter/config-{{ sap_monitoring_nr }}-SQL.json
  ansible.builtin.file:
    path: /etc/hanadb_exporter/config-{{ sap_monitoring_nr }}-SQL.json
    state: absent
  ignore_errors: true

- name: Delete file /etc/sap_host_exporter/sap_host_exporter-{{ sap_monitoring_nr }}-ASCS.yaml
  ansible.builtin.file:
    path: /etc/sap_host_exporter/sap_host_exporter-{{ sap_monitoring_nr }}-ASCS.yaml
    state: absent
  ignore_errors: true

- name: Delete file /etc/sap_host_exporter/sap_host_exporter-{{ sap_monitoring_nr }}-HANA.yaml
  ansible.builtin.file:
    path: /etc/sap_host_exporter/sap_host_exporter-{{ sap_monitoring_nr }}-HANA.yaml
    state: absent
  ignore_errors: true

- name: Delete file /etc/sap_host_exporter/sap_host_exporter-{{ sap_monitoring_nr }}-DI-*.yaml
  ansible.builtin.shell: /usr/bin/rm -f /etc/sap_host_exporter/sap_host_exporter-{{ sap_monitoring_nr }}-DI-*.y*ml
  ignore_errors: true
