---
# The role will install the SAP-HANA-client and SAP hdbcli which is used by hanadb_exporter

- name: Install python3-pip
  ansible.builtin.zypper:
    name: python3-pip
    state: present
  tags: python3-pip

- name: Chmod 750 on files in directory_sap_tools: (expecting file in {{ directory_sap_tools }}:)
  ansible.builtin.file:
    path: "{{ directory_sap_tools }}"
    state: directory
    owner: root
    group: root
    mode: '0750'
    recurse: true

- name: Extract the SAP HANA Client from the SAR-file with SAPCAR
  ansible.builtin.shell:
    cmd: "{{ directory_sap_tools }}/SAPCAR_*.EXE -xvf {{ directory_sap_tools }}/IMDB_CLIENT*.SAR"
    chdir: "{{ directory_sap_tools }}"

- name: Executing hdbinst to install the SAP HANA client
  ansible.builtin.command:
    cmd: "{{ directory_sap_tools }}/SAP_HANA_CLIENT/hdbinst --path=/usr/sap/hdbclient"
    chdir: "{{ directory_sap_tools }}/SAP_HANA_CLIENT/"

- name: Install the SAP HANA python driver
  ansible.builtin.shell: "pip install /usr/sap/hdbclient/hdbcli-*.tar.gz"

- name: Allow execution of hdbcli to non-root users
  ansible.builtin.shell:
    cmd: "chmod -R a+rx /usr/lib64/python3.*/site-packages/hdbcli/*"
    #warn: false
