# ------------------------------------------------------------------------
# Copyright 2021, 2022 IBM Corp. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------
---
### this role preconfigures LPAR for SAP installation requirement. Based on SAP_SOLUTION input, saptune configures the system for HANA or NETWEAVER.

# subscribing to SuSE subscription
# Add repos for installing SLES packages required for SAP installation
- name: Register SuSE and enable repos
  shell: |
   SUSEConnect -r {{ suse_subscription.key }}  -e {{ suse_subscription.username }}
   SUSEConnect -p sle-module-public-cloud/{{suse_subscription.release}}/ppc64le
  when: suse_subscription is defined

# multipathd daemon is checked whether its up or not. If not, it is started. 
- name: Ensure multipathd daemon is running
  service:
   name: multipathd
   state: started 

# For modification on network interfaces, create a dictionary of interfaces
- name: Create interfaces dictionary
  set_fact:
   interfaces: "{{ interfaces | default({}) | combine( {item: hostvars[ inventory_hostname ] ['ansible_' + item ]} ) }}"
  with_items: "{{ ansible_interfaces | replace('-', '_') }}"


# to make the above changes persistent across reboot.
- name: Set jumboframes permanently so it is valid after reboots for all networks except eth0 and lo
  lineinfile:
   dest: "/etc/sysconfig/network/ifcfg-{{ item.key }}"
   regexp: "^MTU"
   line: "MTU='9000'"
  with_dict: "{{ interfaces }}"
  when:
  - "item.value.ipv4.address is defined"
  - "host_ip is not defined or item.value.ipv4.address != host_ip"
  - "item.key != 'lo'"
  - "item.value.mtu != 9000"

# to set jumbo frame changes persistent across reboot.
- name: Set ETHTOOL_OPT ON permanently so it is valid after reboots for all networks except eth0 and lo
  lineinfile:
   dest: "/etc/sysconfig/network/ifcfg-{{ item.key }}"
   regexp: "^ETHTOOL_OPT"
   line: "ETHTOOL_OPT='-K {{ item.key }} tso on'"
  with_dict: "{{ interfaces }}"
  when:
  - "item.value.ipv4.address is defined"
  - "host_ip is not defined or item.value.ipv4.address != host_ip"
  - "item.key != 'lo'"

# to reinforce changes in current boot 
- name: Restart network 
  service:
    name: network 
    state: restarted

# following task checked for SAPTUNE profile on system and apply {{ SAP_SOLUTION }} profile if not applied. Also check for saptune rpm installation
- name: Checking for saptune package installation
  zypper:
    name: saptune
    state: present

- name: Check if {{ SAP_SOLUTION | upper }} solution is applied or not 
  shell: "saptune solution enabled"
  register: saptune_status
 
- name: Tune SLES for SAP {{ SAP_SOLUTION | upper }}
  shell: "saptune solution apply {{ SAP_SOLUTION | upper }}"
  when: saptune_status.stdout.find("{{ SAP_SOLUTION | upper }}") == -1

- name: Activate SLES tuning for SAP {{ SAP_SOLUTION | upper }}
  shell: "saptune daemon start"

# to Insure that NFS and rpcbind daemon are up. 
- name: Ensure NFS client is running
  service:
   name: nfs
   state: started
   enabled: yes

- name: Ensure rpcbind is running
  service:
   name: rpcbind
   state: started
   enabled: yes
