- name: OS registration for RHEL
  ansible.builtin.include_tasks: "rhel.yml"
  when: ansible_distribution is match("RedHat*")
  
- name: OS registration for SLES
  ansible.builtin.include_tasks: "sles.yml"
  when: ansible_distribution is match("SLES*")