- name: OS registration for RHEL
  ansible.builtin.include_tasks: "powervs_fls.yml"
  when: suse_subscription is not defined and rhel_subscription is not defined

- name: OS registration for RHEL (BYOL)
  ansible.builtin.include_tasks: "rhel_byol.yml"
  when: ansible_distribution is match("RedHat*") and rhel_subscription is defined
  
- name: OS registration for SLES (BYOL)
  ansible.builtin.include_tasks: "sles_byol.yml"
  when: ansible_distribution is match("SLES*") and suse_subscription is defined