---
# Subscribing to SUSE subscription
- name: Register Suse and enable repos
  when: byol is defined
  vars:
    use_proxy: "{{ byol.server_proxy_hostname is defined and byol.server_proxy_port is defined }}"
    proxy_str: "{{ byol.server_proxy_hostname|string + ':' + byol.server_proxy_port|string if use_proxy else omit }}"
    proxy_env:
      http_proxy: "{{ proxy_str }}"
      https_proxy: "{{ proxy_str }}"
  environment: "{{ proxy_env if use_proxy else {} }}"
  block:
    - name: Register SUSE
      ansible.builtin.shell: |
        SUSEConnect -r {{ byol.password }}  -e {{ byol.username }}

    - name: Enable Repos
      ansible.builtin.shell: |
        SUSEConnect -p sle-module-public-cloud/{{ ansible_distribution_version }}/ppc64le
