---
### This role does OS registration for a SLES LPAR.
- name: Subscribing to Full Linux® subscription for Power Systems Virtual Servers
  when: full_linux_subscription is defined
  block:
    # Creating backup of readme file, to be restored later
    - name: Copy /usr/share/powervs-fls/powervs-fls-readme.md file
      ansible.builtin.copy:
        src: /usr/share/powervs-fls/powervs-fls-readme.md
        dest: /usr/share/powervs-fls/powervs-fls-readme.md_copy
        mode: preserve

    # Getting cloud-init, to update proxy server and port
    - name: Update cloud-init command with proxy server details
      ansible.builtin.shell: grep cloud-init /usr/share/powervs-fls/powervs-fls-readme.md | grep -vi private
      register: cloud_init_command

    # Backing up the log file and removing it for latest use
    - name: Take a backup of /var/log/powervs-fls.log file
      ansible.builtin.copy:
        src: /var/log/powervs-fls.log
        dest: /var/log/powervs-fls.log.backup
        mode: preserve
      ignore_errors: true

    - name: Delete the /var/log/powervs-fls.log file
      ansible.builtin.file:
        path: /var/log/powervs-fls.log
        state: absent

    # Execute the cloud-init command as in readme
    - name: Execute cloud-init command
      ansible.builtin.command: "{{ cloud_init_command.stdout }} {{ private_proxy_ip_port }}"

    # Wait for successful completion of registration. It will timeout in 300 seconds, if search text is not found
    - name: Wait until the string "Successfully completed SLES subscription registration process"" is in the file /var/log/powervs-fls.log before continuing
      ansible.builtin.wait_for:
        path: /var/log/powervs-fls.log
        search_regex: "Successful completed SLES subscription registration process"
      register: check_for_subscription_success
      ignore_errors: true

    - name: Restoring /usr/share/powervs-fls/powervs-fls-readme.md file
      ansible.builtin.copy:
        src: /usr/share/powervs-fls/powervs-fls-readme.md_copy
        dest: /usr/share/powervs-fls/powervs-fls-readme.md
        mode: preserve

    - name: Delete the backup file
      ansible.builtin.file:
        path: /usr/share/powervs-fls/powervs-fls-readme.md_copy
        state: absent

    - name: Fail if registration fails.
      ansible.builtin.fail:
        msg: "Full Linux Subscription failed, Please debug manually and take corrective action. Logs available at /var/log/powervs-fls.log"
      when: check_for_subscription_success.failed | bool

# Subscribing to SUSE subscription
- name: Register SUSE and enable repos
  ansible.builtin.shell: |
    SUSEConnect -r {{ suse_subscription.key }}  -e {{ suse_subscription.username }}
    SUSEConnect -p sle-module-public-cloud/{{ suse_subscription.release }}/ppc64le
  when: suse_subscription is defined
