---
# Subscribing to SUSE subscription
- name: Register SUSE
  ansible.builtin.shell: |
    SUSEConnect -r {{ byol.password }}  -e {{ byol.username }}
  environment:
    http_proxy: "{{ byol.server_proxy_hostname + ':' + byol.server_proxy_port | default(omit) }}"
    https_proxy: "{{ byol.server_proxy_hostname + ':' + byol.server_proxy_port | default(omit) }}"
  when: byol is defined

- name: Enable Repos
  ansible.builtin.shell: |
    SUSEConnect -p sle-module-public-cloud/{{ ansible_distribution_version }}/ppc64le
  environment:
    http_proxy: "{{ byol.server_proxy_hostname + ':' + byol.server_proxy_port | default(omit) }}"
    https_proxy: "{{ byol.server_proxy_hostname + ':' + byol.server_proxy_port | default(omit) }}"
  when: byol is defined
