---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
  - name: 10.20.10.6
provisioner:
  name: ansible
  inventory:
    links:
      hosts: ../../hosts
      host_vars: ../../host_vars/
verifier:
  name: ansible
