---
## This role pre-configures LPAR for SAP HANA or NETWEAVER based on value set for sap_solution variable.

- name: Ensure required variable is defined
  ansible.builtin.assert:
    that:
      - "{{ sap_solution is defined }}"
      - "{{ sap_domain is defined }}"
    fail_msg: |
      The variable 'sap_solution' is not defined. Please define it in your inventory, group_vars, or as an extra variable.
      The variable 'sap_domain' is not defined. Please define it in your inventory, group_vars, or as an extra variable.

- name: Tune RHEL for SAP
  ansible.builtin.include_tasks: "rhel.yml"
  when: ansible_distribution is match("RedHat*") and sap_solution is defined

- name: Tune SLES for SAP
  ansible.builtin.include_tasks: "sles.yml"
  when: ansible_distribution is match("SLES*") and sap_solution is defined
