# Tuning for SAP on RHEL
- name: Run SAP general preconfigure
  ansible.builtin.include_role:
    name: sap_general_preconfigure
  vars:
    sap_general_preconfigure_fail_if_reboot_required: false
- name: Run SAP HANA preconfigure
  ansible.builtin.include_role:
    name: sap_hana_preconfigure
  vars:
    sap_hana_preconfigure_fail_if_reboot_required: false
  when:
    - sap_solution is match("HANA")
- name: Run SAP Netweaver preconfigure
  ansible.builtin.include_role:
    name: sap_netweaver_preconfigure
  when:
    - sap_solution is match("NETWEAVER")
