---
- name: Executing roles for PowerVS and enable client services, fs and swap creation, preparing RHEL for SAP
  hosts: all
  roles:
    - { role: ibm.power_linux_sap.powervs_install_services, when: server_config is defined }
    - { role: ibm.power_linux_sap.powervs_client_enable_services, when: client_config is defined }
    - { role: ibm.power_linux_sap.powervs_fs_creation, when: disks_configuration is defined }
    - { role: ibm.power_linux_sap.powervs_swap_creation, when: swap_disk_wwn is defined }
    - { role: ibm.power_linux_sap.powervs_prepare_rhel_sap, when: sap_solution is defined }
    - { role: ibm.power_linux_sap.powervs_install_services, when: server_config is defined }
    - { role: ibm.power_linux_sap.powervs_client_enable_services, when: client_config is defined }
