---
name: Molecule Test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install molecule==5.1.0 ansible-core
      - name: Test with molecule
        run: |
          ansible-galaxy collection install ansible.posix
          ansible-galaxy collection install community.general
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/private.key
          sudo chmod 600 ~/.ssh/private.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          eval `ssh-agent -s`
          echo PUBLIC_IP=${PUBLIC_IP}
          ssh-add ~/.ssh/private.key
          molecule drivers
          find . -name molecule
          cd ./IBM/ansible-power-linux-sap/
          molecule test
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SAH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
          PUBLIC_IP: ${{secrets.PUBLIC_IP}}
          
